### ISSUE TITLE
Multiple pipelines

### ISSUE THREAD

**Issue by joe-mohan** [everythinginjs/strapi-plugin-update-static-content#6]
Hey, awesome package.

Have you considered adding the ability to trigger different pipelines?

**Comment by everythinginjs** [comment]
Thanks for the feedback, currently you can only use one workflow at the same time but it would be a nice idea.

**Comment by IndigoServiceUser** [comment]
> Thanks for the feedback, currently you can only use one workflow at the same time but it would be a nice idea.

This would be a neat feature to have! We currently have multiple sites relying on the same strapi server.

**Comment by schwarzi33** [comment]
Hey.. Your plugin is really awesome.
We would also have the need for the feature to trigger different pipelines. Are there any news about it? For us it would be sufficient to change the workflow within the settings page :) 

Thanks and BR

**Comment by schwarzi33** [comment]
@everythinginjs do you have any news regarding this feature?
It would be really crucial for us to have such possibility! 

Thanks a lot in advance.
