### ISSUE TITLE
"Confirm" popup before trigger button

### ISSUE THREAD

**Issue by mrabello23** [everythinginjs/strapi-plugin-update-static-content#7]
Nice job with this plugin! 👍🏼 
It will be very helpful add a "Confirm action" popup before click the trigger button.

**Comment by everythinginjs** [comment]
Hey @mrabello23 , thanks for feedback I will consider that.

**Comment by everythinginjs** [comment]
Hey @mrabello23 , I added this feature in v2.0.7.

**Comment by mrabello23** [comment]
Awsome, thank you so much!!
