### ISSUE TITLE
Error after leave plugin page

### ISSUE THREAD

**Issue by mrabello23** [everythinginjs/strapi-plugin-update-static-content#8]
When I openned plugin's page and changed right after to another page, I got this error on console and a white screen.
Same behavior within plugin's configuration page.

STRAPI VERSION
v4.20.3

NODE VERSION
v18.19.1

![image](https://github.com/everythinginjs/strapi-plugin-update-static-content/assets/2198051/1639444a-6d77-4bbb-96bd-e64a893ebf29)

**Comment by everythinginjs** [comment]
Hi @mrabello23 , 

Thanks for the issue, I will check it.

**Comment by everythinginjs** [comment]
Hey @mrabello23, 
the issue has been fixed ✅ in v1.0.9.
I also would like to say that a major update will be coming this weekend I am working on it.

**Comment by mrabello23** [comment]
Hey @everythinginjs 
I really appreciate it, thanks you!
